name: Build and Release EXE for Python application

on:
  push:
    tags:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          architecture: "x64"

      - name: Install Dependencies
        run: |
          pip install opencv-python numpy Pillow scikit-image keyboard pywin32

      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: vrchat-drawing-script.py
          mode: app
          enable-plugins: tk-inter

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: build/vrchat-drawing-script.exe
          include-hidden-files: true

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: build/vrchat-drawing-script.exe
